### ISSUE TITLE
Can't add attachment by uploading from computer

### ISSUE THREAD

**Issue by pro-sumer** [accatyyc/fastmate#1]
Adding an attachment by uploading from my computer does not work; after selecting that option a file dialog should open to select a file. Unfortunately this dialog does not appear.

Note that it does appear if I embed the [FastMail](https://fastmail.com) web interface in [Fluid](https://fluidapp.com) and try to add an attachment by uploading from my computer in that App.

**Comment by accatyyc** [comment]
Hey! Thanks for the report, I’ll take a look at it. Does drag and drop work?

**Comment by pro-sumer** [comment]
> Does drag and drop work?

Unfortunately not.

I can only drag files to text fields; the full name of the file (path, name, extension) will be dropped (as text), not the actual (text or binary) content.

**Comment by accatyyc** [comment]
Hey! The issue has been fixed in version 1.0.2. Thanks for reporting!

**Comment by accatyyc** [comment]
The issue has been fixed in version 1.0.2. Thanks again for reporting!
