### ISSUE TITLE
⌘N (New mail) and ⌘F (Find) not working?

### ISSUE THREAD

**Issue by pro-sumer** [accatyyc/fastmate#2]
Both ⌘N (New mail) and ⌘F (Find) are not working for me.

Expected results:
* ⌘N opens new compose window (like FastMail's `c` shortcut)
* ⌘F puts cursor in search field (like FastMail's `/` shortcut)

Actual results:
* ⌘N (only) flashes "File" in menu bar
* ⌘F (only) flashes "Edit" in menu bar

**Comment by pro-sumer** [comment]
- macOS High Sierra 10.13.6
- mail view

**Comment by accatyyc** [comment]
I figured it out. The shortcuts stop working when the sidebar is hidden, even if it’s enabled again.

I’ll try to fix it later today!

**Comment by accatyyc** [comment]
Hey again, here's a beta that should fix the ⌘N-shortcut. Can you verify that it works?

I haven't figured out a way to improve the ⌘F-shortcut, however, that one seems to always work for me. Can you verify that you still have a problem with ⌘F in this beta version?

[Fastmate.zip](https://github.com/accatyyc/fastmate/files/2510621/Fastmate.zip)

**Comment by pro-sumer** [comment]
Yes, both ⌘N and ⌘F are working now in the FastMail production interface.

**Comment by pro-sumer** [comment]
Now both are not working again... Trying to figure out why. 

Observation:
* worked when I tested with an external wired (Apple) keyboard earlier today
* never worked when I tested with the internal keyboard (of a MacBook Pro)

(don't have an external keyboard available right now to verify)

**Comment by pro-sumer** [comment]
Sorry, apparently I was testing with the FastMail beta interface today...

Both ⌘N and ⌘F are working (with the external and the internal keyboard) on the production interface.

**Comment by accatyyc** [comment]
Cool! I should check out the beta interface and make sure Fastmate works with it. Thanks for letting me know about it. I'll submit a new version with the fixes for now.

**Comment by accatyyc** [comment]
Fixed in [v1.0.3](https://github.com/accatyyc/fastmate/releases/tag/v1.0.3)
